version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 119919
      POSTGRES_DB: usersmanagement
    ports:
      - 5432:5432